package mera.mera_v2.repository;

import mera.mera_v2.entity.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;

public interface OrderRepository extends JpaRepository<Order, Long> {

  List<Order> findAllByIdIn(List<Long> ids);

  @Query("SELECT o.id FROM Order o WHERE o.id IN :ids")
  List<Long> findExistingIds(@Param("ids") List<Long> ids);

  @Modifying
  @Query(value = """
      INSERT INTO orders (id, order_code, shop_id, page_id, customer_id, conversation_id, post_id,
          ad_id, creator_id, assigning_seller_id, assigning_care_id, marketer_id, last_editor_id,
          warehouse_id, status, sub_status, status_name, bill_full_name, bill_phone_number, bill_email,
          shipping_full_name, shipping_phone_number, shipping_address, shipping_full_address,
          shipping_province_id, shipping_province_name, shipping_district_id, shipping_district_name,
          shipping_commune_id, shipping_commune_name, shipping_country_code, shipping_post_code,
          order_sources, order_sources_name, ads_source, p_utm_source, p_utm_medium, p_utm_campaign,
          p_utm_content, p_utm_term, p_utm_id, is_livestream, is_live_shopping, total_price,
          total_price_after_sub_discount, total_discount, shipping_fee, surcharge, tax, cod,
          money_to_collect, prepaid, cash, transfer_money, charged_by_momo, charged_by_card,
          charged_by_qrpay, exchange_payment, exchange_value, partner_fee, return_fee, fee_marketplace,
          buyer_total_amount, levera_point, is_free_shipping, is_exchange_order, is_calculation_tax,
          is_smc, customer_pay_fee, received_at_shop, partner, tracking_link, time_send_partner,
          estimate_delivery_date, returned_reason, returned_reason_name, note, note_print, link,
          time_assign_seller, time_assign_care, inserted_at, updated_at, lt_type, tick, created_at,
          customer_address, customer_name, customer_phone, last_editor_name, order_id,
          partner_delivery_name, partner_tracking_id, account, account_name, order_link, raw_data)
      VALUES (:id, :order_code, :shop_id, :page_id, :customer_id, :conversation_id, :post_id,
          :ad_id, :creator_id, :assigning_seller_id, :assigning_care_id, :marketer_id, :last_editor_id,
          :warehouse_id, :status, :sub_status, :status_name, :bill_full_name, :bill_phone_number, :bill_email,
          :shipping_full_name, :shipping_phone_number, :shipping_address, :shipping_full_address,
          :shipping_province_id, :shipping_province_name, :shipping_district_id, :shipping_district_name,
          :shipping_commune_id, :shipping_commune_name, :shipping_country_code, :shipping_post_code,
          :order_sources, :order_sources_name, :ads_source, :p_utm_source, :p_utm_medium, :p_utm_campaign,
          :p_utm_content, :p_utm_term, :p_utm_id, :is_livestream, :is_live_shopping, :total_price,
          :total_price_after_sub_discount, :total_discount, :shipping_fee, :surcharge, :tax, :cod,
          :money_to_collect, :prepaid, :cash, :transfer_money, :charged_by_momo, :charged_by_card,
          :charged_by_qrpay, :exchange_payment, :exchange_value, :partner_fee, :return_fee, :fee_marketplace,
          :buyer_total_amount, :levera_point, :is_free_shipping, :is_exchange_order, :is_calculation_tax,
          :is_smc, :customer_pay_fee, :received_at_shop, :partner, :tracking_link, :time_send_partner,
          :estimate_delivery_date, :returned_reason, :returned_reason_name, :note, :note_print, :link,
          :time_assign_seller, :time_assign_care, :inserted_at, :updated_at, :lt_type, :tick, :created_at,
          :customer_address, :customer_name, :customer_phone, :last_editor_name, :order_id,
          :partner_delivery_name, :partner_tracking_id, :account, :account_name, :order_link, :raw_data)
      ON DUPLICATE KEY UPDATE
          order_code = VALUES(order_code), shop_id = VALUES(shop_id), page_id = VALUES(page_id),
          customer_id = VALUES(customer_id), conversation_id = VALUES(conversation_id),
          post_id = VALUES(post_id), ad_id = VALUES(ad_id), creator_id = VALUES(creator_id),
          assigning_seller_id = VALUES(assigning_seller_id), assigning_care_id = VALUES(assigning_care_id),
          marketer_id = VALUES(marketer_id), last_editor_id = VALUES(last_editor_id),
          warehouse_id = VALUES(warehouse_id), status = VALUES(status), sub_status = VALUES(sub_status),
          status_name = VALUES(status_name), bill_full_name = VALUES(bill_full_name),
          bill_phone_number = VALUES(bill_phone_number), bill_email = VALUES(bill_email),
          shipping_full_name = VALUES(shipping_full_name), shipping_phone_number = VALUES(shipping_phone_number),
          shipping_address = VALUES(shipping_address), shipping_full_address = VALUES(shipping_full_address),
          shipping_province_id = VALUES(shipping_province_id), shipping_province_name = VALUES(shipping_province_name),
          shipping_district_id = VALUES(shipping_district_id), shipping_district_name = VALUES(shipping_district_name),
          shipping_commune_id = VALUES(shipping_commune_id), shipping_commune_name = VALUES(shipping_commune_name),
          shipping_country_code = VALUES(shipping_country_code), shipping_post_code = VALUES(shipping_post_code),
          order_sources = VALUES(order_sources), order_sources_name = VALUES(order_sources_name),
          ads_source = VALUES(ads_source), p_utm_source = VALUES(p_utm_source), p_utm_medium = VALUES(p_utm_medium),
          p_utm_campaign = VALUES(p_utm_campaign), p_utm_content = VALUES(p_utm_content),
          p_utm_term = VALUES(p_utm_term), p_utm_id = VALUES(p_utm_id), is_livestream = VALUES(is_livestream),
          is_live_shopping = VALUES(is_live_shopping), total_price = VALUES(total_price),
          total_price_after_sub_discount = VALUES(total_price_after_sub_discount),
          total_discount = VALUES(total_discount), shipping_fee = VALUES(shipping_fee),
          surcharge = VALUES(surcharge), tax = VALUES(tax), cod = VALUES(cod),
          money_to_collect = VALUES(money_to_collect), prepaid = VALUES(prepaid), cash = VALUES(cash),
          transfer_money = VALUES(transfer_money), charged_by_momo = VALUES(charged_by_momo),
          charged_by_card = VALUES(charged_by_card), charged_by_qrpay = VALUES(charged_by_qrpay),
          exchange_payment = VALUES(exchange_payment), exchange_value = VALUES(exchange_value),
          partner_fee = VALUES(partner_fee), return_fee = VALUES(return_fee),
          fee_marketplace = VALUES(fee_marketplace), buyer_total_amount = VALUES(buyer_total_amount),
          levera_point = VALUES(levera_point), is_free_shipping = VALUES(is_free_shipping),
          is_exchange_order = VALUES(is_exchange_order), is_calculation_tax = VALUES(is_calculation_tax),
          is_smc = VALUES(is_smc), customer_pay_fee = VALUES(customer_pay_fee),
          received_at_shop = VALUES(received_at_shop), partner = VALUES(partner),
          tracking_link = VALUES(tracking_link), time_send_partner = VALUES(time_send_partner),
          estimate_delivery_date = VALUES(estimate_delivery_date), returned_reason = VALUES(returned_reason),
          returned_reason_name = VALUES(returned_reason_name), note = VALUES(note),
          note_print = VALUES(note_print), link = VALUES(link), time_assign_seller = VALUES(time_assign_seller),
          time_assign_care = VALUES(time_assign_care), updated_at = VALUES(updated_at),
          lt_type = VALUES(lt_type), tick = VALUES(tick), created_at = VALUES(created_at),
          customer_address = VALUES(customer_address), customer_name = VALUES(customer_name),
          customer_phone = VALUES(customer_phone), last_editor_name = VALUES(last_editor_name),
          order_id = VALUES(order_id), partner_delivery_name = VALUES(partner_delivery_name),
          partner_tracking_id = VALUES(partner_tracking_id), account = VALUES(account),
          account_name = VALUES(account_name), order_link = VALUES(order_link), raw_data = VALUES(raw_data)
      """, nativeQuery = true)
  void upsertOrder(@Param("id") Long id, @Param("order_code") String orderCode,
      @Param("shop_id") Long shopId, @Param("page_id") String pageId,
      @Param("customer_id") String customerId, @Param("conversation_id") String conversationId,
      @Param("post_id") String postId, @Param("ad_id") String adId,
      @Param("creator_id") String creatorId, @Param("assigning_seller_id") String assigningSellerId,
      @Param("assigning_care_id") String assigningCareId, @Param("marketer_id") String marketerId,
      @Param("last_editor_id") String lastEditorId, @Param("warehouse_id") String warehouseId,
      @Param("status") Integer status, @Param("sub_status") String subStatus,
      @Param("status_name") String statusName, @Param("bill_full_name") String billFullName,
      @Param("bill_phone_number") String billPhoneNumber, @Param("bill_email") String billEmail,
      @Param("shipping_full_name") String shippingFullName,
      @Param("shipping_phone_number") String shippingPhoneNumber,
      @Param("shipping_address") String shippingAddress,
      @Param("shipping_full_address") String shippingFullAddress,
      @Param("shipping_province_id") String shippingProvinceId,
      @Param("shipping_province_name") String shippingProvinceName,
      @Param("shipping_district_id") String shippingDistrictId,
      @Param("shipping_district_name") String shippingDistrictName,
      @Param("shipping_commune_id") String shippingCommuneId,
      @Param("shipping_commune_name") String shippingCommuneName,
      @Param("shipping_country_code") String shippingCountryCode,
      @Param("shipping_post_code") String shippingPostCode,
      @Param("order_sources") Integer orderSources,
      @Param("order_sources_name") String orderSourcesName,
      @Param("ads_source") String adsSource,
      @Param("p_utm_source") String pUtmSource, @Param("p_utm_medium") String pUtmMedium,
      @Param("p_utm_campaign") String pUtmCampaign, @Param("p_utm_content") String pUtmContent,
      @Param("p_utm_term") String pUtmTerm, @Param("p_utm_id") String pUtmId,
      @Param("is_livestream") Integer isLivestream,
      @Param("is_live_shopping") Integer isLiveShopping,
      @Param("total_price") Double totalPrice,
      @Param("total_price_after_sub_discount") java.math.BigDecimal totalPriceAfterSubDiscount,
      @Param("total_discount") java.math.BigDecimal totalDiscount,
      @Param("shipping_fee") java.math.BigDecimal shippingFee,
      @Param("surcharge") java.math.BigDecimal surcharge, @Param("tax") java.math.BigDecimal tax,
      @Param("cod") java.math.BigDecimal cod,
      @Param("money_to_collect") java.math.BigDecimal moneyToCollect,
      @Param("prepaid") java.math.BigDecimal prepaid, @Param("cash") java.math.BigDecimal cash,
      @Param("transfer_money") java.math.BigDecimal transferMoney,
      @Param("charged_by_momo") java.math.BigDecimal chargedByMomo,
      @Param("charged_by_card") java.math.BigDecimal chargedByCard,
      @Param("charged_by_qrpay") java.math.BigDecimal chargedByQrpay,
      @Param("exchange_payment") java.math.BigDecimal exchangePayment,
      @Param("exchange_value") java.math.BigDecimal exchangeValue,
      @Param("partner_fee") java.math.BigDecimal partnerFee,
      @Param("return_fee") java.math.BigDecimal returnFee,
      @Param("fee_marketplace") java.math.BigDecimal feeMarketplace,
      @Param("buyer_total_amount") java.math.BigDecimal buyerTotalAmount,
      @Param("levera_point") Integer leveraPoint,
      @Param("is_free_shipping") Integer isFreeShipping,
      @Param("is_exchange_order") Boolean isExchangeOrder,
      @Param("is_calculation_tax") Boolean isCalculationTax,
      @Param("is_smc") Integer isSmc, @Param("customer_pay_fee") Boolean customerPayFee,
      @Param("received_at_shop") Integer receivedAtShop,
      @Param("partner") String partner, @Param("tracking_link") String trackingLink,
      @Param("time_send_partner") java.time.LocalDateTime timeSendPartner,
      @Param("estimate_delivery_date") java.time.LocalDate estimateDeliveryDate,
      @Param("returned_reason") String returnedReason,
      @Param("returned_reason_name") String returnedReasonName,
      @Param("note") String note, @Param("note_print") String notePrint,
      @Param("link") String link,
      @Param("time_assign_seller") java.time.LocalDateTime timeAssignSeller,
      @Param("time_assign_care") java.time.LocalDateTime timeAssignCare,
      @Param("inserted_at") java.time.LocalDateTime insertedAt,
      @Param("updated_at") java.time.LocalDateTime updatedAt,
      @Param("lt_type") String ltType, @Param("tick") Integer tick,
      @Param("created_at") java.time.LocalDateTime createdAt,
      @Param("customer_address") String customerAddress,
      @Param("customer_name") String customerName,
      @Param("customer_phone") String customerPhone,
      @Param("last_editor_name") String lastEditorName,
      @Param("order_id") Long orderId,
      @Param("partner_delivery_name") String partnerDeliveryName,
      @Param("partner_tracking_id") String partnerTrackingId,
      @Param("account") String account, @Param("account_name") String accountName,
      @Param("order_link") String orderLink, @Param("raw_data") String rawData);
}